### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vsilent001** [jasonleaster/FaceDetection#9]
Constructing AdaBoost from existed model data
Construction finished

Traceback (most recent call last):
  File "C:/Users/rpa-s/Desktop/FaceDetection-master/FaceDetection/EFace.py", line 27, in <module>
    rectangles = det.scanImgOverScale(imgSingleChannel)
  File "C:\Users\rpa-s\Desktop\FaceDetection-master\FaceDetection\detector.py", line 114, in scanImgOverScale
    rectangles += self.scanImgAtScale(model, image, scale)
  File "C:\Users\rpa-s\Desktop\FaceDetection-master\FaceDetection\detector.py", line 54, in scanImgAtScale
    subImages[idx] = Image(Mat = image[y:y+SEARCH_WIN_HEIGHT, x:x+SEARCH_WIN_WIDTH])
  File "C:\Users\rpa-s\Desktop\FaceDetection-master\FaceDetection\image.py", line 33, in __init__
    assert Mat != None
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

我更改了EFace中的TEST_IMG的路径到指定的文件上，运行之后出现了请问这个报错应该怎么处理...

**Comment by jasonleaster** [comment]
@Vsilent001 会单步调试吗？
[How-To-Ask-Questions-The-Smart-Way](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)

项目可能需要比较坚实的"编程基础"。
